load Models/neosha_Spring_englinp1.mat

% Plot a bunch of usual figures together all in one go

    f=md.materials.rho_freshwater./(md.materials.rho_ice.*md.geometry.thickness).*(md.results.TransientSolution(end).HydrologyHead-md.geometry.base); % Fraction of overburden
    f(f<0)=0;
    Re=abs(md.results.TransientSolution(end).HydrologyBasalFlux)./1.787e-6; % Reynolds number

% plotmodel(md,'data',md.results.TransientSolution(end).HydrologyHead,'title','Head (m)','colormap','parula',...
%     'data',md.results.TransientSolution(end).HydrologyBasalFlux,'title','Basal Flux (m^2 s^{-1})','colormap','parula',...
%     'data',md.results.TransientSolution(end).HydrologyGapHeight,'title','Gap Height (m)','colormap','parula',...
%     'data',md.results.TransientSolution(end).EffectivePressure,'title','Effective Pressure (Pa)','colormap','parula',...
%     'data',log10(md.results.TransientSolution(end).HydrologyBasalFlux),'title','log_{10}[Basal Flux] (m^2 s^{-1})','colormap','parula',...
%     'data',log10(md.results.TransientSolution(end).HydrologyGapHeight),'title','log_{10}[Gap Height] (m)','colormap','parula',...
%     'data',f,'title','Fraction of Overburden','colormap','parula',...
%     'data',log10(Re),'title','log_{10}[Re]','colormap','parula')

%plotmodel(md,'data',md.results.TransientSolution(end).HydrologyHead,'title','Head (m) EI7','colormap','parula')
%plotmodel(md, 'data', md.geometry.surface, 'title', 'Surface Elevation (m)') 
%plotmodel(md, 'data', log10(Re), 'title', 'log_{10} [Re]', 'colormap', 'parula')

%Re=md.results.TransientSolution(end).HydrologyBasalFlux(posm)./nu; 
%plotmodel(md, 'data', md.results.TransientSolution(end).HydrologyGapHeight(posm).^3.*md.constants.g./(12*nu.*(1+omega.*Re)));
plotmodel(md, 'data', md.results.TransientSolution(end).HydrologyBasalFlux, 'title','Basal Flux (m^2 s^{-1})','colormap','parula')

% plotmodel(md,'data','mesh','title','mesh',...
%     'data',md.geometry.base,'title','Bed Elevation (m)',...
%     'data',md.geometry.surface,'title','Surface Elevation (m)',...
%     'data',md.geometry.thickness,'title','Ice Thickness (m)',...
%     'data',md.initialization.vel,'title','Surface Velocity (m a^{-1})')

% plotmodel(md,'data',md.results.TransientSolution(end).HydrologyBasalFlux,'title','Basal Flux (m^2 s^{-1})',...
%     'data',log10(md.results.TransientSolution(end).HydrologyBasalFlux),'title','log_{10}[Basal Flux] (m^2 s^{-1})')

% plotmodel(md,'data',md.results.TransientSolution(end).HydrologyGapHeight,'title','Gap Height (m)',...
%     'data',log10(md.results.TransientSolution(end).HydrologyGapHeight),'title','log_{10}[Gap Height] (m)')

% plotmodel(md,'data',md.results.TransientSolution(end).HydrologyHead,'title','Head (m)',...
%     'data',md.results.TransientSolution(end).EffectivePressure,'title','Effective Pressure (Pa)',...
%     'data',md.results.TransientSolution(end).DegreeOfChannelization,'title','Deg. of Channelization')